// ---------------------------------------------------------------
// LAYER CONFIG
// ---------------------------------------------------------------
// Add one entry per GeoJSON file. Put the actual .geojson files
// in the /data folder — file names below must match exactly.
//
//   id       -> unique short id, no spaces
//   label    -> name shown in the layer panel
//   file     -> path inside /data
//   type     -> "point" | "line" | "polygon"
//   color    -> hex color used to style this layer (ignored for points if
//               "icon" is set below)
//   visible  -> true = layer is on by default
//   popupFields -> which properties to show when a feature is clicked
//                  (leave as [] to auto-show all properties)
//   icon     -> OPTIONAL, points only. Path to a custom icon image
//               (put the image file in /icons). Example:
//               icon: { url: "icons/tree.png", width: 24, height: 24 }
//               Omit "icon" entirely to use a plain colored dot.
// ---------------------------------------------------------------

const SUPABASE_URL = "https://agcybjjgaytxsibghniw.supabase.co";
const SUPABASE_KEY = "sb_publishable_MuPHkvO4GOGR575Udn1h8A_emQCy4Qc";

const FACTIONS = [
  { name: "Ottoman Empire", color: "#905744" },
  { name: "Vatican", color: "#ccb1b1" },
  { name: "Spain", color: "#c5a808" },
  { name: "Imperial", color: "#97996b" },
  { name: "Safavid", color: "#ffce47" },
  { name: "Venice", color: "#42b9ff" },
  { name: "Dutch", color: "#d86343" },
  { name: "Liege", color: "#c594aa" },
  { name: "Ragusa", color: "#95b265" },
  { name: "Genoa", color: "#ff63ea" },
  { name: "Hesse-Kassel", color: "#271e3a" },
  { name: "Hesse-Darmstadt", color: "#97996b" },
  { name: "Sweden", color: "#2a3c82" },
  { name: "Portugal", color: "#216d1e" },
  { name: "France", color: "#4769b7" },
  { name: "England", color: "#ff4264" },
  { name: "Denmark", color: "#00ffff" },
  { name: "Cologne", color: "#a94064" },
  { name: "Palatinate", color: "#65938c" },
  { name: "Habsburg", color: "#f7d78b" },
  { name: "Tuscany", color: "#7c9bb5" },
  { name: "Morocco", color: "#f3a6b2" },
  { name: "Trier", color: "#d6b2bd" },
  { name: "Saxony", color: "#df8482" },
  { name: "Polish-Lithuanian Commonwealth", color: "#df8482" },
  { name: "Mainz", color: "#81538c" },
  { name: "Hanover", color: "#d38f52" },
  { name: "Bavaria", color: "#96bbce" },
  { name: "Holstein-Gottorp", color: "#426fe2" },
  { name: "Savoy", color: "#daa572" },
  { name: "Prussia", color: "#78685d" },
  { name: "Parma", color: "#c4cb7c" },
  { name: "Modena", color: "#5a9260" },
  { name: "Mantua", color: "#cdba9f" },
  { name: "Lorraine", color: "#8db7ab" },
  { name: "Russia", color: "#95a37e" },
  { name: "Switzerland", color: "#f2b9b4" },
  { name: "Algiers", color: "#576e6a" },
  { name: "Tunis", color: "#612f0a" },
  { name: "None", color: "#FFFFFF" }
];

const LAYERS = [
    {
    id: "Main_Roads",
    label: "Main Roads",
    file: "data/Main Roads.geojson",
    type: "line",
    color: "#613611",
    visible: true,
    popupFields: [],
    interactive: false
  },
  {
    id: "France",
    label: "Kingdom of France",
    file: "data/FranceReal.geojson",
    type: "polygon",
    color: "#4769b7",
    visible: true,
    popupFields: []
  },
{
  id: "SecondaryRoads",
  label: "Secondary Roads",
  file: "data/SecondaryRoads.geojson",
  type: "line",
  color: "#613611",
  visible: true,
  popupFields: [],
  dashed: true,
  interactive: false
},
{
  id: "pre_cities",
  label: "Cities",
  file: "data/pre_cities.geojson",
  type: "point",
  color: "#e8a33d",
  visible: true,
  popupFields: [],
  labelField: "city",
  minFeatureZoom: 6,
  minLabelZoom: 7,
  cluster: false,
  clusterMaxZoom: 6,
  priorityField: "citypop_le"
},
{
  id: "bastions",
  label: "Bastions",
  file: "data/Bastions.geojson",
  type: "point",
  color: "#FFFFFF",
  visible: true,
  popupFields: [],
  icon: { url: "icons/Bastion.svg", width: 15, height: 15 },
  labelField: "name",
  minFeatureZoom: 6,
  minLabelZoom: 7,
  cluster: false,
  clusterMaxZoom: 6,
  ownershipTable: "Bastions",
  ownershipIdColumn: "Bastion_id"
},
{
  id: "cities",
  label: "Other Cities",
  file: "data/mycities.geojson",
  type: "point",
  color: "#e8a33d",
  visible: true,
  popupFields: [],
  labelField: "names",
  minFeatureZoom: 6,
  minLabelZoom: 7,
  cluster: false,
  clusterMaxZoom: 6
},
{
  id: "Bicoque",
  label: "Bicoque",
  file: "data/Bicoque.geojson",
  type: "point",
  color: "#FFFFFF",
  visible: true,
  popupFields: [],
  icon: { url: "icons/Basic_Fort.svg", width: 15, height: 15 },
  labelField: "names",
  minFeatureZoom: 6,
  minLabelZoom: 7,
  cluster: false,
  clusterMaxZoom: 6,
  ownershipTable: "Bicoques",
  ownershipIdColumn: "Bicoque_id"
},
{
  id: "Forts",
  label: "Forts",
  file: "data/Forts.geojson",
  type: "point",
  color: "#FFFFFF",
  visible: true,
  popupFields: [],
  icon: { url: "icons/Castle.svg", width: 15, height: 15 },
  labelField: "names",
  minFeatureZoom: 6,
  minLabelZoom: 7,
  cluster: false,
  clusterMaxZoom: 6,
  ownershipTable: "Forts",
  ownershipIdColumn: "Fort_id"
},
{
  id: "Liege",
  label: "Prince-Bishopric of Liege",
  file: "data/Prince-Bishopric_Liege.geojson",
  type: "polygon",
  color: "#c594aa",
  visible: true,
  popupFields: [],
},
{
  id: "Netherlands",
  label: "Republic of the Seven United Netherlands",
  file: "data/Netherlands.geojson",
  type: "polygon",
  color: "#d86343",
  visible: true,
  popupFields: [],
},
{
  id: "Spain",
  label: "Spanish Monarchy",
  file: "data/Spain.geojson",
  type: "polygon",
  color: "#c5a808",
  visible: true,
  popupFields: [],
},
{
  id: "Swiss",
  label: "Swiss Confederacy",
  file: "data/Swiss.geojson",
  type: "polygon",
  color: "#f2b9b4",
  visible: true,
  popupFields: [],
},
{
  id: "Rus",
  label: "Tsardom of Russia",
  file: "data/Rus.geojson",
  type: "polygon",
  color: "#95a37e",
  visible: true,
  popupFields: [],
},
{
  id: "Turkmen",
  label: "Turkmen Khanate",
  file: "data/TurkmenKhanate.geojson",
  type: "polygon",
  color: "#85b66f",
  visible: true,
  popupFields: [],
},
{
  id: "Mulhouse",
  label: "Allied City of Mulhouse",
  file: "data/Mulhouse.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Salzburg",
  label: "Archbishopric of Salzburg",
  file: "data/Salzburg.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Mzab",
  label: "Cities of Mzab",
  file: "data/Mzab.geojson",
  type: "polygon",
  color: "#e15989",
  visible: true,
  popupFields: [],
},
{
  id: "Laghouat",
  label: "City of Laghouat",
  file: "data/Laghouat.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "PLC",
  label: "Polish Lithuanian Commonwealth",
  file: "data/PLC.geojson",
  type: "polygon",
  color: "#df8482",
  visible: true,
  popupFields: [],
},
{
  id: "Andorra",
  label: "Principality of Andorra",
  file: "data/Andorra.geojson",
  type: "polygon",
  color: "#e8718d",
  visible: true,
  popupFields: [],
},
{
  id: "Lippe",
  label: "County of Lippe",
  file: "data/Lippe.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Brunswick-Wolfenbatle",
  label: "Duchy of Brunswick-Wolfenbuttel",
  file: "data/Brunswick-Wolfenbatle.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Lorraine",
  label: "Duchy of Lorraine",
  file: "data/Lorraine.geojson",
  type: "polygon",
  color: "#8db7ab",
  visible: true,
  popupFields: [],
},
{
  id: "Mantua",
  label: "Duchy of Mantua",
  file: "data/Mantua.geojson",
  type: "polygon",
  color: "#cdba9f",
  visible: true,
  popupFields: [],
},
{
  id: "MassaCarrara",
  label: "Duchy of Massa and Carrara",
  file: "data/MassaCarrara.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Mecklenburg",
  label: "Duchy of Mecklenburg",
  file: "data/Mecklenburg.geojson",
  type: "polygon",
  color: "#5a9260",
  visible: true,
  popupFields: [],
},
{
  id: "ModenaReggio",
  label: "Duchy of Modena and Reggio",
  file: "data/ModenaReggio.geojson",
  type: "polygon",
  color: "#5a9260",
  visible: true,
  popupFields: [],
},
{
  id: "Palatinate-Sulzbach",
  label: "Duchy of Palatinate-Sulzbach",
  file: "data/Palatinate-Sulzbach.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "ParmaPiacenza",
  label: "Duchy of Parma and Piacenza",
  file: "data/ParmaPiacenza.geojson",
  type: "polygon",
  color: "#c4cb7c",
  visible: true,
  popupFields: [],
},
{
  id: "Prussia",
  label: "Duchy of Prussia and Electorate of Brandenburg",
  file: "data/Prussia.geojson",
  type: "polygon",
  color: "#695141",
  visible: true,
  popupFields: [],
},
{
  id: "Savoy",
  label: "Duchy of Savoy",
  file: "data/Savoy.geojson",
  type: "polygon",
  color: "#daa572",
  visible: true,
  popupFields: [],
},
{
  id: "Saxe-Coburg",
  label: "Duchy of Saxe-Coburg",
  file: "data/Saxe-Coburg.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Saxe-Eisenach",
  label: "Duchy of Saxe-Eisenach",
  file: "data/Saxe-Eisenach.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Saxe-Gotha-Altenburg",
  label: "Duchy of Saxe-Gotha-Altenburg",
  file: "data/Saxe-Gotha-Altenburg.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Saxe-Hildburghausen",
  label: "Duchy of Saxe-Hildburghausen",
  file: "data/Saxe-Hildburghausen.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Saxe-Meiningen",
  label: "Duchy of Saxe Meiningen",
  file: "data/Saxe-Meiningen.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Schleswig-Holstein-Gottorp",
  label: "Duchy of Schleswig-Holstein-Gottorp",
  file: "data/Schleswig-Holstein-Gottorp.geojson",
  type: "polygon",
  color: "#426fe2",
  visible: true,
  popupFields: [],
},
{
  id: "Wurttemberg",
  label: "Duchy of Wurttemberg",
  file: "data/Wurttemberg.geojson",
  type: "polygon",
  color: "#c6b15f",
  visible: true,
  popupFields: [],
},
{
  id: "Zweibrucken",
  label: "Duchy of Zweibrucken",
  file: "data/Zweibrucken.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Bavaria",
  label: "Duchy of Bavaria",
  file: "data/Bavaria.geojson",
  type: "polygon",
  color: "#96bbce",
  visible: true,
  popupFields: [],
},
{
  id: "BrunswickLuneburg",
  label: "Duchy of Brunswick-Luneburg",
  file: "data/BrunswickLuneburg.geojson",
  type: "polygon",
  color: "#d38f52",
  visible: true,
  popupFields: [],
},
{
  id: "Cologne",
  label: "Electorate of Cologne",
  file: "data/Cologne.geojson",
  type: "polygon",
  color: "#a94064",
  visible: true,
  popupFields: [],
},
{
  id: "Mainz",
  label: "Electorate of Mainz",
  file: "data/Mainz.geojson",
  type: "polygon",
  color: "#81538c",
  visible: true,
  popupFields: [],
},
{
  id: "Saxony",
  label: "Electorate of Saxony",
  file: "data/Saxony.geojson",
  type: "polygon",
  color: "#df8482",
  visible: true,
  popupFields: [],
},
{
  id: "Trier",
  label: "Electorate of Trier",
  file: "data/Trier.geojson",
  type: "polygon",
  color: "#d6b2bd",
  visible: true,
  popupFields: [],
},
{
  id: "Adrar",
  label: "Emirate of the Adrar",
  file: "data/Adrar.geojson",
  type: "polygon",
  color: "#e8718d",
  visible: true,
  popupFields: [],
},
{
  id: "Morocco",
  label: "Emirate of the Fez and Morocco",
  file: "data/Morocco.geojson",
  type: "polygon",
  color: "#f3a6b2",
  visible: true,
  popupFields: [],
},
{
  id: "Tuscany",
  label: "Grand Duchy of Tuscany",
  file: "data/Tuscany.geojson",
  type: "polygon",
  color: "#7c9bb5",
  visible: true,
  popupFields: [],
},
{
  id: "Habsburg",
  label: "Habsburg Monarchy",
  file: "data/Habsburg.geojson",
  type: "polygon",
  color: "#f7d78b",
  visible: true,
  popupFields: [],
},
{
  id: "Wittelsbach",
  label: "Elector Palatinate",
  file: "data/Wittelsbach.geojson",
  type: "polygon",
  color: "#65938c",
  visible: true,
  popupFields: [],
},
{
  id: "Aberlingen",
  label: "Imperial City Aberlingen",
  file: "data/Aberlingen.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Augsburg",
  label: "Imperial City Augsburg",
  file: "data/Augsburg.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Biberach",
  label: "Imperial City Biberach",
  file: "data/Biberach.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Bremen",
  label: "Imperial City Bremen",
  file: "data/Bremen.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Buchhorn",
  label: "Imperial City Buchhorn",
  file: "data/Buchhorn.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Cologne",
  label: "Imperial City Cologne",
  file: "data/Cologne.geojson",
  type: "polygon",
  color: "#a94064",
  visible: true,
  popupFields: [],
},
{
  id: "Dortmund",
  label: "Imperial City Dortmund",
  file: "data/Dortmund.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Frankfurt",
  label: "Imperial City Frankfurt",
  file: "data/Frankfurt.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Goslar",
  label: "Imperial City Goslar",
  file: "data/Goslar.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Hamburg",
  label: "Imperial City Hamburg",
  file: "data/Hamburg.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Kaufbeuren",
  label: "Imperial City Kaufbeuren",
  file: "data/Kaufbeuren.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Kempten",
  label: "Imperial City Kempten",
  file: "data/Kempten.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Laabeck",
  label: "Imperial City Laabeck",
  file: "data/Laabeck.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Lindau",
  label: "Imperial City Lindau",
  file: "data/Lindau.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Mahlhausen",
  label: "Imperial City Mahlhausen",
  file: "data/Mahlhausen.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Memmingen",
  label: "Imperial City Memmingen",
  file: "data/Memmingen.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Nuremberg",
  label: "Imperial City Nuremberg",
  file: "data/Nuremberg.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Regensburg",
  label: "Imperial City Regensburg",
  file: "data/Regensburg.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Reutlingen",
  label: "Imperial City Reutlingen",
  file: "data/Reutlingen.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Rothenburg",
  label: "Imperial City Rothenburg",
  file: "data/Rothenburg.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Rottweil",
  label: "Imperial City Rottweil",
  file: "data/Rottweil.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "SchwabischesHall",
  label: "Imperial City Schwabisches Hall",
  file: "data/SchwabischesHall.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Schweinfurt",
  label: "Imperial City Schweinfurt",
  file: "data/Schweinfurt.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Ulm",
  label: "Imperial City Ulm",
  file: "data/Ulm.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Wetzlar",
  label: "Imperial City Wetzlar",
  file: "data/Wetzlar.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Beni Abbes",
  label: "Kalaat of the Beni Abbes",
  file: "data/Beni Abbes.geojson",
  type: "polygon",
  color: "#85b66f",
  visible: true,
  popupFields: [],
},
{
  id: "Balakan",
  label: "Khanate of Balakan",
  file: "data/Balakan.geojson",
  type: "polygon",
  color: "#91522d",
  visible: true,
  popupFields: [],
},
{
  id: "Tarki",
  label: "Khanate of Tarki",
  file: "data/Tarki.geojson",
  type: "polygon",
  color: "#c43c39",
  visible: true,
  popupFields: [],
},
{
  id: "Denmark",
  label: "Kingdoms of Denmark-Norway",
  file: "data/Denmark.geojson",
  type: "polygon",
  color: "#00ffff",
  visible: true,
  popupFields: [],
},
{
  id: "England-Ireland",
  label: "Kingdom of England and Ireland",
  file: "data/England-Ireland.geojson",
  type: "polygon",
  color: "#ff4264",
  visible: true,
  popupFields: [],
},
{
  id: "Portugal",
  label: "Kingdom of Portugal",
  file: "data/Portugal.geojson",
  type: "polygon",
  color: "#216d1e",
  visible: true,
  popupFields: [],
},
{
  id: "Scotland",
  label: "Kingdom of Scotland",
  file: "data/Scotland in PU with England.geojson",
  type: "polygon",
  color: "#407bef",
  visible: true,
  popupFields: [],
},
{
  id: "Sweden",
  label: "Kingdom of Sweden",
  file: "data/Sweden.geojson",
  type: "polygon",
  color: "#2a3c82",
  visible: true,
  popupFields: [],
},
{
  id: "Kartli-Kakheti",
  label: "Kingdom of Kartli and Kakheti",
  file: "data/Kartli-Kakheti.geojson",
  type: "polygon",
  color: "#85b66f",
  visible: true,
  popupFields: [],
},
{
  id: "Hesse-Darmstadt",
  label: "Landgraviate of Hesse-Darmstadt",
  file: "data/Hesse-Darmstadt.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Hesse-Kassel",
  label: "Landgraviate of Hesse-Kassel",
  file: "data/Hesse-Kassel.geojson",
  type: "polygon",
  color: "#271e3a",
  visible: true,
  popupFields: [],
},
{
  id: "Lucca",
  label: "Lordship of Lucca",
  file: "data/Lucca.geojson",
  type: "polygon",
  color: "#5a73e1",
  visible: true,
  popupFields: [],
},
{
  id: "Nassau",
  label: "Lordships of the House of Nassau",
  file: "data/House of Nassau.geojson",
  type: "polygon",
  color: "#996e3e",
  visible: true,
  popupFields: [],
},
{
  id: "Baden",
  label: "Margravate of Baden",
  file: "data/Baden.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Brandenburg-Ansbach",
  label: "Margravate of Brandenburg-Ansbach",
  file: "data/Brandenburg-Ansbach.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Brandenburg-Bayreuth",
  label: "Margravate of Brandenburg-Bayreuth",
  file: "data/Brandenburg-Bayreuth.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Al-Dir'iyah",
  label: "Oasis of Al-Dir'iyah",
  file: "data/Al-Dir'iyah.geojson",
  type: "polygon",
  color: "#d5b43c",
  visible: true,
  popupFields: [],
},
{
  id: "Malta",
  label: "Order of Saint-John of Malta",
  file: "data/Malta.geojson",
  type: "polygon",
  color: "#85b66f",
  visible: true,
  popupFields: [],
},
{
  id: "Basel",
  label: "Prince-Bishopric of Basel",
  file: "data/Basel.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Timbuktu",
  label: "Pasha of Timbuktu",
  file: "data/Basel.geojson",
  type: "polygon",
  color: "#91522d",
  visible: true,
  popupFields: [],
},
{
  id: "Passau",
  label: "Prince-Bishopric of Passau",
  file: "data/Passau.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Ratzeburg",
  label: "Prince-Bishopric of Ratzeburg",
  file: "data/Ratzeburg.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Anhalt-Bernburg",
  label: "Principality of Anhalt-Bernburg",
  file: "data/Anhalt-Bernburg.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Anhalt-Dessau",
  label: "Principality of Anhalt-Dessau",
  file: "data/Anhalt-Dessau.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Anhalt-Kaathen",
  label: "Principality of Anhalt-Kothen",
  file: "data/Anhalt-Kaathen.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Anhalt-Zerbst",
  label: "Principality of Anhalt-Zerbst",
  file: "data/Anhalt-Zerbst.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Hohenzollern-Hechingen",
  label: "Principality of Hohenzollern-Hechingen",
  file: "data/Hohenzollern-Hechingen.geojson",
  type: "polygon",
  color: "#445787",
  visible: true,
  popupFields: [],
},
{
  id: "Hohenzollern-Sigmari",
  label: "Principality of Hohenzollern-Sigmaringen",
  file: "data/Hohenzollern-Sigmari.geojson",
  type: "polygon",
  color: "#445787",
  visible: true,
  popupFields: [],
},
{
  id: "Masserano",
  label: "Principality of Masserano",
  file: "data/Masserano.geojson",
  type: "polygon",
  color: "#e15989",
  visible: true,
  popupFields: [],
},
{
  id: "Monaco",
  label: "Principality of Monaco",
  file: "data/Monaco.geojson",
  type: "polygon",
  color: "#987db7",
  visible: true,
  popupFields: [],
},
{
  id: "Orange",
  label: "Principality of Orange",
  file: "data/Orange.geojson",
  type: "polygon",
  color: "#ff8403",
  visible: true,
  popupFields: [],
},
{
  id: "Piombino",
  label: "Principality of Piombino",
  file: "data/Piombino.geojson",
  type: "polygon",
  color: "#e8718d",
  visible: true,
  popupFields: [],
},
{
  id: "Salm-Salm",
  label: "Principality of Salm-Salm",
  file: "data/Salm-Salm.geojson",
  type: "polygon",
  color: "#f3a6b2",
  visible: true,
  popupFields: [],
},
{
  id: "Svaneti",
  label: "Principality of Svaneti",
  file: "data/Svaneti.geojson",
  type: "polygon",
  color: "#d5b43c",
  visible: true,
  popupFields: [],
},
{
  id: "Waldeck-Pyrmont",
  label: "Principality of Waldeck-Pyrmont",
  file: "data/Waldeck-Pyrmont.geojson",
  type: "polygon",
  color: "#85b66f",
  visible: true,
  popupFields: [],
},
{
  id: "Genoa",
  label: "Republic of Genoa",
  file: "data/Genoa.geojson",
  type: "polygon",
  color: "#ff63ea",
  visible: true,
  popupFields: [],
},
{
  id: "Ragusa",
  label: "Republic of Ragusa",
  file: "data/Ragusa.geojson",
  type: "polygon",
  color: "#95b265",
  visible: true,
  popupFields: [],
},
{
  id: "San Marino",
  label: "Republic of San Marino",
  file: "data/San Marino.geojson",
  type: "polygon",
  color: "#d86343",
  visible: true,
  popupFields: [],
},
{
  id: "Venice",
  label: "Republic of Venice",
  file: "data/Republic of Venice.geojson",
  type: "polygon",
  color: "#42b9ff",
  visible: true,
  popupFields: [],
},
{
  id: "Persia",
  label: "Sefevid Empire of Persia",
  file: "data/Sefevid Empire of Persia.geojson",
  type: "polygon",
  color: "#ffce47",
  visible: true,
  popupFields: [],
},
{
  id: "Lahsa",
  label: "Small States of Lahsa",
  file: "data/Small States of Lahsa.geojson",
  type: "polygon",
  color: "#f3a6b2",
  visible: true,
  popupFields: [],
},
{
  id: "Small States of HRE",
  label: "Small States of HRE",
  file: "data/Small HRE States.geojson",
  type: "polygon",
  color: "#97996b",
  visible: true,
  popupFields: [],
},
{
  id: "Church",
  label: "State of the Church",
  file: "data/State of the Church.geojson",
  type: "polygon",
  color: "#ccb1b1",
  visible: true,
  popupFields: [],
},
{
  id: "Ottoman",
  label: "Sublime Ottoman State",
  file: "data/Sublime Ottoman State.geojson",
  type: "polygon",
  color: "#905744",
  visible: true,
  popupFields: [],
},
{
  id: "Funj",
  label: "Sultnate of Funj",
  file: "data/Sultnate of Funj.geojson",
  type: "polygon",
  color: "#e15989",
  visible: true,
  popupFields: [],
},
{
  id: "10m Rivers",
  label: "Rivers",
  file: "data/10mrivers.geojson",
  type: "line",
  color: "#487bb6",
  visible: true,
  popupFields: [],
  interactive: false
}

  // Add more layers here, e.g.: 
  // {
  //   id: "rivers",
  //   label: "Rivers",
  //   file: "data/rivers.geojson",
  //   type: "line",
  //   color: "#c594aa",
  //   visible: false,
  //   popupFields: ["name", "length_km"]
  // },
];

// Initial map view [lat, lng], zoom
const MAP_CENTER = [54.5, 15.5];
const MAP_ZOOM = 4;
